require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CountryTeamsController do

  # This should return the minimal set of attributes required to create a valid
  # CountryTeam. As you add validations to CountryTeam, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CountryTeamsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all country_teams as @country_teams" do
      country_team = CountryTeam.create! valid_attributes
      get :index, {}, valid_session
      assigns(:country_teams).should eq([country_team])
    end
  end

  describe "GET show" do
    it "assigns the requested country_team as @country_team" do
      country_team = CountryTeam.create! valid_attributes
      get :show, {:id => country_team.to_param}, valid_session
      assigns(:country_team).should eq(country_team)
    end
  end

  describe "GET new" do
    it "assigns a new country_team as @country_team" do
      get :new, {}, valid_session
      assigns(:country_team).should be_a_new(CountryTeam)
    end
  end

  describe "GET edit" do
    it "assigns the requested country_team as @country_team" do
      country_team = CountryTeam.create! valid_attributes
      get :edit, {:id => country_team.to_param}, valid_session
      assigns(:country_team).should eq(country_team)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CountryTeam" do
        expect {
          post :create, {:country_team => valid_attributes}, valid_session
        }.to change(CountryTeam, :count).by(1)
      end

      it "assigns a newly created country_team as @country_team" do
        post :create, {:country_team => valid_attributes}, valid_session
        assigns(:country_team).should be_a(CountryTeam)
        assigns(:country_team).should be_persisted
      end

      it "redirects to the created country_team" do
        post :create, {:country_team => valid_attributes}, valid_session
        response.should redirect_to(CountryTeam.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved country_team as @country_team" do
        # Trigger the behavior that occurs when invalid params are submitted
        CountryTeam.any_instance.stub(:save).and_return(false)
        post :create, {:country_team => {}}, valid_session
        assigns(:country_team).should be_a_new(CountryTeam)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CountryTeam.any_instance.stub(:save).and_return(false)
        post :create, {:country_team => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested country_team" do
        country_team = CountryTeam.create! valid_attributes
        # Assuming there are no other country_teams in the database, this
        # specifies that the CountryTeam created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CountryTeam.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => country_team.to_param, :country_team => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested country_team as @country_team" do
        country_team = CountryTeam.create! valid_attributes
        put :update, {:id => country_team.to_param, :country_team => valid_attributes}, valid_session
        assigns(:country_team).should eq(country_team)
      end

      it "redirects to the country_team" do
        country_team = CountryTeam.create! valid_attributes
        put :update, {:id => country_team.to_param, :country_team => valid_attributes}, valid_session
        response.should redirect_to(country_team)
      end
    end

    describe "with invalid params" do
      it "assigns the country_team as @country_team" do
        country_team = CountryTeam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CountryTeam.any_instance.stub(:save).and_return(false)
        put :update, {:id => country_team.to_param, :country_team => {}}, valid_session
        assigns(:country_team).should eq(country_team)
      end

      it "re-renders the 'edit' template" do
        country_team = CountryTeam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CountryTeam.any_instance.stub(:save).and_return(false)
        put :update, {:id => country_team.to_param, :country_team => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested country_team" do
      country_team = CountryTeam.create! valid_attributes
      expect {
        delete :destroy, {:id => country_team.to_param}, valid_session
      }.to change(CountryTeam, :count).by(-1)
    end

    it "redirects to the country_teams list" do
      country_team = CountryTeam.create! valid_attributes
      delete :destroy, {:id => country_team.to_param}, valid_session
      response.should redirect_to(country_teams_url)
    end
  end

end
