require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FocusGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # FocusGroup. As you add validations to FocusGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FocusGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all focus_groups as @focus_groups" do
      focus_group = FocusGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:focus_groups).should eq([focus_group])
    end
  end

  describe "GET show" do
    it "assigns the requested focus_group as @focus_group" do
      focus_group = FocusGroup.create! valid_attributes
      get :show, {:id => focus_group.to_param}, valid_session
      assigns(:focus_group).should eq(focus_group)
    end
  end

  describe "GET new" do
    it "assigns a new focus_group as @focus_group" do
      get :new, {}, valid_session
      assigns(:focus_group).should be_a_new(FocusGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested focus_group as @focus_group" do
      focus_group = FocusGroup.create! valid_attributes
      get :edit, {:id => focus_group.to_param}, valid_session
      assigns(:focus_group).should eq(focus_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FocusGroup" do
        expect {
          post :create, {:focus_group => valid_attributes}, valid_session
        }.to change(FocusGroup, :count).by(1)
      end

      it "assigns a newly created focus_group as @focus_group" do
        post :create, {:focus_group => valid_attributes}, valid_session
        assigns(:focus_group).should be_a(FocusGroup)
        assigns(:focus_group).should be_persisted
      end

      it "redirects to the created focus_group" do
        post :create, {:focus_group => valid_attributes}, valid_session
        response.should redirect_to(FocusGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved focus_group as @focus_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        FocusGroup.any_instance.stub(:save).and_return(false)
        post :create, {:focus_group => {}}, valid_session
        assigns(:focus_group).should be_a_new(FocusGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FocusGroup.any_instance.stub(:save).and_return(false)
        post :create, {:focus_group => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested focus_group" do
        focus_group = FocusGroup.create! valid_attributes
        # Assuming there are no other focus_groups in the database, this
        # specifies that the FocusGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FocusGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => focus_group.to_param, :focus_group => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested focus_group as @focus_group" do
        focus_group = FocusGroup.create! valid_attributes
        put :update, {:id => focus_group.to_param, :focus_group => valid_attributes}, valid_session
        assigns(:focus_group).should eq(focus_group)
      end

      it "redirects to the focus_group" do
        focus_group = FocusGroup.create! valid_attributes
        put :update, {:id => focus_group.to_param, :focus_group => valid_attributes}, valid_session
        response.should redirect_to(focus_group)
      end
    end

    describe "with invalid params" do
      it "assigns the focus_group as @focus_group" do
        focus_group = FocusGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FocusGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => focus_group.to_param, :focus_group => {}}, valid_session
        assigns(:focus_group).should eq(focus_group)
      end

      it "re-renders the 'edit' template" do
        focus_group = FocusGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FocusGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => focus_group.to_param, :focus_group => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested focus_group" do
      focus_group = FocusGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => focus_group.to_param}, valid_session
      }.to change(FocusGroup, :count).by(-1)
    end

    it "redirects to the focus_groups list" do
      focus_group = FocusGroup.create! valid_attributes
      delete :destroy, {:id => focus_group.to_param}, valid_session
      response.should redirect_to(focus_groups_url)
    end
  end

end
